// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuYcj4a1Jx1On89ZMH3x8UHPB6-rmxdjQ',
    appId: '1:72556658495:web:b677d9975e7b4fd4cf9d8a',
    messagingSenderId: '72556658495',
    projectId: 'petwalks-ef2a9',
    authDomain: 'petwalks-ef2a9.firebaseapp.com',
    storageBucket: 'petwalks-ef2a9.appspot.com',
    measurementId: 'G-SQ7QND68X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv1t5tDMcp9fxGW5FVaRmyJR5fbz4Y1OU',
    appId: '1:72556658495:android:d0b3e2e31a80d813cf9d8a',
    messagingSenderId: '72556658495',
    projectId: 'petwalks-ef2a9',
    storageBucket: 'petwalks-ef2a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs_rMdB2A3Lwxwth2sgZhH1jUMTAOZko0',
    appId: '1:72556658495:ios:a952d5e00f30aacfcf9d8a',
    messagingSenderId: '72556658495',
    projectId: 'petwalks-ef2a9',
    storageBucket: 'petwalks-ef2a9.appspot.com',
    iosBundleId: 'com.example.petwalksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs_rMdB2A3Lwxwth2sgZhH1jUMTAOZko0',
    appId: '1:72556658495:ios:a952d5e00f30aacfcf9d8a',
    messagingSenderId: '72556658495',
    projectId: 'petwalks-ef2a9',
    storageBucket: 'petwalks-ef2a9.appspot.com',
    iosBundleId: 'com.example.petwalksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuYcj4a1Jx1On89ZMH3x8UHPB6-rmxdjQ',
    appId: '1:72556658495:web:5717b69d91277cf1cf9d8a',
    messagingSenderId: '72556658495',
    projectId: 'petwalks-ef2a9',
    authDomain: 'petwalks-ef2a9.firebaseapp.com',
    storageBucket: 'petwalks-ef2a9.appspot.com',
    measurementId: 'G-H35L4YE032',
  );
}
